kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: aqsa-twistlock
  labels: 
    app-volume: twistlock
spec: 
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: managed-premium